services:
  hp27s:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    container_name: hp27s
    volumes:
      - ./public_html:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - TZ=pacific/Auckland
