# File: `docker-compose.yaml`
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    container_name: wherethefuckaremypants
    volumes:
      - ../public_html:/usr/share/nginx/html
    ports:
      - "8013:80"
    environment:
      - TZ=pacific/Auckland
