# File: `docker-compose.yaml`
services:
  wherethefuckaremypants:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: prod
    container_name: wherethefuckaremypants
    restart: unless-stopped

    environment:
      - TZ=Pacific/Auckland
    env_file:
      - ../.env
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${APP_NAME}-secure.rule=Host(`${APP_DOMAIN}`)  || Host(`www.${APP_DOMAIN}`)
      - traefik.http.routers.${APP_NAME}-secure.entrypoints=websecure
      # HTTPS
   #   - traefik.http.routers.${APP_NAME}-secure.rule=Host(`${APP_DOMAIN}`)  || Host(`www.${APP_DOMAIN}`)
  #    - traefik.http.routers.${APP_NAME}-secure.entrypoints=websecure
#      - traefik.http.routers.${APP_NAME}-secure.tls=true
 #     - traefik.http.routers.${APP_NAME}-secure.tls.certresolver=le

      # Internal port
      # - traefik.http.services.${APP_NAME}.loadbalancer.server.port=80


networks:
  web:
    external: true